# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'moodyTimer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod "RecordButton"

  # Pods for moodyTimer

  target 'moodyTimerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'moodyTimerUITests' do
    # Pods for testing
  end

end
